version: 1.0.{build}-{branch}

branches:
  only:
  - master
  - dev

image: Visual Studio 2015

platform: Any CPU

build:
  parallel: true

before_build: 
  - dotnet restore
  
install:
 - ps: .\Bootstrap.ps1

build_script:
 - dotnet run -p src\CodeCakeBuilder -nointeraction
 
test: off
